name: Test Deploy
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Tests
              run: npm run test
            - name: Build
              run: |
                    npm run build
                    echo "Building deployment..."
            - name: Github Context
              run: echo "${{ toJSON(github) }}"

